
spring:
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/market"
    username: "jonathan"
    password: "market"
    driver-class-name: org.postgresql.Driver

server:
  port: 80